### ISSUE TITLE
Sobol now available in scipy

### ISSUE THREAD

**Issue by willu47** [virgesmith/humanleague#34]
Hi @virgesmith - you might be interested to know that a Sobol generator has been implemented in [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.qmc.Sobol.html).  We're using this in the SALib library rather than our own implementation.

**Comment by virgesmith** [comment]
Hi @willu47 thanks for the heads up, useful to know. It's used internally so I'd need to be able to call it from C++ - which, while doable, is a bit clunky and inefficient.
