### ISSUE TITLE
info about this package

### ISSUE THREAD

**Issue by n400peanuts** [virgesmith/humanleague#42]
Hello. 

I have found this package by chance on github, and I am very interested! 

I am currently using the [mipfp](https://github.com/jojo-/mipfp) package in R to synthetise a populations used later on for modelling purposes in Python (package [here](https://github.com/covid19ABM/comma)). I was looking for a semi-replica of this package in Python, to have everything in one place, however I am not sure if the multidimensional IPF is integrated, and I can't find any example/documentation showing an example on how to use the package in Python.
Can you please give advice? help in some way? 

best wishes and many thanks

**Comment by virgesmith** [comment]
Hi

Multidimensional IPF is available in python using `humanleague.ipf(...)`. There aren't any explicit examples, but when you install *humanleague* your IDE should display docstrings inline. You could also look at the test code [here](https://github.com/virgesmith/humanleague/blob/main/tests/test_all.py#L103). Hope this helps
